Repository halojasatech/nest-backend-boilerplate, pull requests merged in 2020-10, with the labels that each got.

#9 Add support for Gitpod
  .env.example
  .gitpod.Dockerfile
  .gitpod.yml
  script/.gitpod.sh
Labels: new feature

#6 Winston ES Logging Enhancement
  script/entry-point.sh
  src/app/middleware/apm-agent.middleware.ts
  src/app/util/data-censoring/index.ts
  src/app/util/data-censoring/sensitive-key.json
  src/app/util/logger/formater/default-format.ts
  src/app/util/logger/formater/http-format.ts
  src/app/util/logger/index.ts
  src/app/util/logger/logger-transport.ts
  src/app/util/mask-json/collection-key.json
  src/app/util/mask-json/index.ts
  src/controllers/check-email.controller.ts
  src/main.ts
Labels: enhancement, good first issue

#7 Draft: Implement HTTP Exception Filters
  src/app.module.ts
  src/app/exceptions/http-exception.filter.ts
  src/app/exceptions/http-exception.ts
  src/app/middleware/header.middleware.ts
  src/app/util/interceptors/response.interceptor.ts
  src/app/util/logger/logger-transport.ts
  src/app/util/mask-json/index.ts
  src/services/check-email.service.ts
Labels: enhancement, help wanted, new feature

#11 Improving Logger
  src/app.module.ts
  src/app/util/logger/formater/default-format.ts
  src/app/util/logger/formater/http-format.ts
  src/app/util/logger/logger-transport.ts
  src/controllers/check-email.controller.ts
  src/controllers/sample.ts
  src/services/check-email.service.ts
  src/services/sample.service.ts
Labels: enhancement

#16 Fixing Jest Module Resolver & improve sample test file
  package.json
  src/__test__/app.e2e-spec.ts
  src/app.module.ts
  src/services/sample.service.ts
Labels: bug, enhancement

#17 dependency: 💍 Add dependabot
  .github/dependabot.yml
Labels: dependency

#8 Add Redis Library as Key-Value Database
  .env.example
  .gitpod.Dockerfile
  docker-compose.yml
  package-lock.json
  package.json
  src/app/config/app.ts
  src/app/library/index.ts
  src/app/library/redis/redis.lib.ts
  src/main.ts
Labels: help wanted, new feature

#18 Add database dir on Jest moduleNameMapper
  package.json
  src/app.module.ts
  src/app/util/interceptors/response.interceptor.ts
  src/database/connect.ts
  src/main.ts
Labels: enhancement

#19 Add Sample Seeder Script
  .eslintrc.js
  docker-compose.yml
  docs/database/database.erd.puml
  package-lock.json
  package.json
  script/entry-point.sh
  script/seeder.ts
  src/app.module.ts
  src/controllers/sample.ts
  src/database/index.ts
  src/database/models/user-authentication.model.ts
  src/database/models/user-data.model.ts
  src/database/models/user.model.ts
  src/database/seeder/index.ts
  src/database/seeder/seeder.module.ts
  src/database/seeder/users.seed.ts
  src/repositories/userAuthentication.repository.ts
  src/services/sample.service.ts
  tsconfig.json
Labels: enhancement, new feature
